### ISSUE TITLE
Same webhook for different kinds of resource

### ISSUE THREAD

**Issue by leogr** [slok/kubewebhook#36]
Currently, `WebhookConfig` requires a specific object to be passed, like the following:
```
mcfg := mutatingwh.WebhookConfig{
		Name: "podAnnotate",
		Obj:  &corev1.Pod{},
	}
```

On the other hand, the `MutatingWebhookConfiguration` Kubernetes' configuration allows to register the same webhook for different kinds of resource, for example:
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook
  labels:
    app: webhook
    kind: mutator
webhooks:
  - name: webhook.example.net
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: "/mutating"
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods", "deployments", "replicationcontrollers", "replicasets", "daemonsets", "statefulsets", "jobs", "cronjobs"]
```

Is it possibile to configure `kubewebhook` in a way that all resource can be handled by the same webhook?

Looking into the code, it seems not possible (I might be wrong) because `WebhookConfig.Obj` is used to de-serialize the object, so it works only with objects of the same kind. IMHO, it's useful to have just one webhook endpoint that can review different kinds of resources.

Let me know, if that is possible in someway.

Thanks in advance!
